--1. CREATE TABLE 
--CREATING A TABLE 
CREATE TABLE employee_ (
	emp_id INT NOT NULL,
	name VARCHAR(40) NOT NULL,
	DOJ DATE,
	phone VARCHAR(20) NOT NULL,
	CONSTRAINT p_employee PRIMARY KEY (emp_id)
)

--2: Alter 
-- ADDING COLUMN 
ALTER TABLE employee_
ADD email VARCHAR(50)

-- DROPING COLUMN
ALTER TABLE employee_
DROP COLUMN name 

--DROP
-- DROP THE TABLE ( REMOVE THE EXISTANCE OF EVERY PIECE OF DATA THAT THE DEFINE TABLE HOLDS)
DROP TABLE employee_
SELECT * FROM employee_